administrator/urls.py
from django.conf.urls import url, include
from administrator import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  url(r'^$', views.dashboard, name='dashboard'),
                  url(r'^login$', views.login, name='login'),
                  url(r'^signout$', views.signout, name='signout'),
                  url(r'^actions$', views.actions, name='actions'),
                  url(r'^damages$', views.fill_damages, name='fill_damages'),
                  url(r'^search_car$', views.search_car, name='search_car'),
                  url(r'^car/list$', views.car_list, name='car_list'),
                  url(r'^contacts$', views.contacts, name='contacts'),
                  url(r'^stock_images$', views.stock_images, name='stock_images'),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.conf.urls import url, include
from main import views
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    url(r'^$', views.home_page, name='home_page'),
    url(r'^browse$', views.car_browse, name='car_browse'),
    url(r'^buying_process', views.buying_process, name='buying_process'),
    url(r'^finance', views.finance, name='finance'),
    # url(r'^about_us', views.about_us, name='about_us'),
    url(r'^faq', views.faq, name='faq'),
    url(r'^car/(?P<car_id>[0-9]+)$', views.car_profile, name='car_profile'),
    url(r'^car/customer/(?P<unique_customer_link>[a-zA-Z0-9]+)$', views.customer_car_view, name='customer_car_view'),
    url(r'^ajax_load_cars$', views.ajax_load_cars, name='ajax_load_cars'),
    url(r'^ajax_load_models$', views.ajax_load_models, name='ajax_load_models'),
    url(r'^showroom/(?P<car_id>[0-9]+)$', views.showroom, name='showroom'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^login/$', views.selfLogin, name='login'),
    url(r'^logout/$', views.selfLogout, name='logout'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

administrator/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

crawler/models.py
from __future__ import unicode_literals

from django.db import models
from django.db.models import Q
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.contrib.staticfiles.templatetags.staticfiles import static
from django.utils import timezone

import managers
import random


class Car(models.Model):
    mo_car_id = models.IntegerField(null=True, blank=True)
    ove_car_id = models.IntegerField(null=True, blank=True)
    ade_car_id = models.IntegerField(null=True, blank=True)
    bg_car_id = models.IntegerField(null=True, blank=True)
    vin = models.CharField(max_length=31)
    stock_number = models.CharField(max_length=31, null=True, blank=True)
    make = models.ForeignKey('Make', null=True, blank=True)
    model = models.ForeignKey('CarModel', null=True, blank=True)
    trim = models.ForeignKey('CarTrim', null=True, blank=True)
    car_model = models.CharField(max_length=255)
    original_price = models.IntegerField(null=True, blank=True)
    final_price = models.IntegerField(null=True, blank=True)
    year = models.SmallIntegerField(null=True, blank=True)
    location = models.ForeignKey('Location', null=True, blank=True)
    grade = models.FloatField(null=True, blank=True)
    last_checking = models.DateTimeField()
    is_it_available = models.BooleanField(default=True)
    available_on_mo = models.BooleanField(default=False)
    available_on_bg = models.BooleanField(default=False)
    available_on_ove = models.BooleanField(default=False)
    available_on_ade = models.BooleanField(default=False)
    mo_removed_at = models.DateTimeField(null=True, blank=True)
    bg_removed_at = models.DateTimeField(null=True, blank=True)
    ove_removed_at = models.DateTimeField(null=True, blank=True)
    ade_removed_at = models.DateTimeField(null=True, blank=True)
    last_updated_time = models.DateTimeField(null=True, blank=True)
    is_rejected = models.BooleanField(default=False)
    rejection_reason = models.CharField(max_length=1023, null=True, blank=True)
    eligible_to_display = models.BooleanField(default=False)
    removed_permanently = models.BooleanField(default=False)
    remain_permatently = models.BooleanField(default=False)
    remain_until = models.DateTimeField(null=True, blank=True)
    unique_customer_link = models.CharField(max_length=255, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    objects = managers.CarManager()
    
    def __unicode__(self):
        return str(self.id)

    def save(self, *args, **kwargs):
        if self.stock_number == None:
            self.stock_number = self.generate_stock_number()
        super(Car, self).save(*args, **kwargs)

    def is_available_eligible(self):
        return (self.is_it_available == True\
                or (self.remain_until != None and self.remain_until > timezone.now())\
                or self.remain_permatently == True)\
               and self.is_rejected == False and self.eligible_to_display == True and self.make.is_visible == True\
               and self.removed_permanently == False

    def generate_stock_number(self):
        return chr(65 + int(random.random() * 26)) + chr(65 + int(random.random() * 26)) + str(
            int(random.random() * 10)) + str(int(random.random() * 10)) + str(int(random.random() * 10)) + str(
            int(random.random() * 10))

    def generate_unique_cutomer_link(self):
        string = []
        id_str = str(self.id)
        chars_count = 12
        mod = chars_count / len(id_str)
        for i in xrange(12):
            string.append(chr(97 + int(random.random() * 26)))

        return ''.join(string[:8]) + id_str + ''.join(string[8:])

    def stock_image(self):
        year = self.year
        car_model = self.model
        car_trim = self.trim

        stock_image_infos = StockImageInfo.objects.filter(
            Q(model=car_model) & (Q(trim=None) | Q(trim=car_trim)) & Q(year=year) & Q(stock_image__view_type='F') & Q(
                stock_image__colors__name__iexact=self.cardetail.exterior))

        if len(stock_image_infos) > 0:
            for stock_image_info in stock_image_infos:
                if stock_image_info.trim != None:
                    return stock_image_info.stock_image.image.url

            return stock_image_infos.first().stock_image.image.url

        return static('img/no_image.png')


class CarDetail(models.Model):
    car = models.OneToOneField('Car')
    detail_html = models.FilePathField()
    vehicle_options = models.TextField(null=True, blank=True)
    miles = models.IntegerField(null=True, blank=True)
    exterior = models.CharField(max_length=255, null=True, blank=True)
    interior = models.CharField(max_length=255, null=True, blank=True)
    engine = models.CharField(max_length=255, null=True, blank=True)
    odor = models.CharField(max_length=255, null=True, blank=True)
    msrp = models.IntegerField(null=True, blank=True)
    announcements = models.CharField(max_length=1000, null=True, blank=True)
    value_added_options = models.CharField(max_length=1000, null=True, blank=True)
    warranty_date = models.DateField(null=True, blank=True)
    drive = models.CharField(max_length=255, null=True, blank=True)
    keys = models.CharField(max_length=255, null=True, blank=True)


class Location(models.Model):
    name = models.CharField(max_length=255)
    shipping_cost = models.IntegerField(default=0)

    def __unicode__(self):
        return self.name


class Make(models.Model):
    name = models.CharField(max_length=255)
    fuel_name = models.CharField(max_length=255)
    is_visible = models.BooleanField(default=True)

    def __unicode__(self):
        return self.name


class CarModel(models.Model):
    name = models.CharField(max_length=255)
    fuel_name = models.CharField(max_length=255)
    make = models.ForeignKey('Make')

    def __unicode__(self):
        return self.name + ', ' + self.make.name


class CarTrim(models.Model):
    name = models.CharField(max_length=255)
    model = models.ForeignKey('CarModel')

    def __unicode__(self):
        return self.name + ', ' + self.model.name + ', ' + self.model.make.name


class Tire(models.Model):
    TIRE_CHOICES = (
        ('LFRNT', 'LFRNT'),
        ('LREAR', 'LREAR'),
        ('RFRNT', 'RFRNT'),
        ('RREAR', 'RREAR'),
        ('SPARE', 'SPARE'),
    )

    car = models.ForeignKey('Car')
    type = models.CharField(max_length=31, choices=TIRE_CHOICES)
    tread = models.CharField(max_length=31, null=True, blank=True)
    brand = models.CharField(max_length=31, null=True, blank=True)
    size = models.CharField(max_length=31, null=True, blank=True)


class Repair(models.Model):
    car = models.ForeignKey('Car')
    repaired = models.CharField(max_length=255)
    condition = models.CharField(max_length=255, null=True, blank=True)
    severity = models.CharField(max_length=255, null=True, blank=True)
    repair_type = models.CharField(max_length=255, null=True, blank=True)


class Damage(models.Model):
    car = models.ForeignKey('Car')
    part = models.CharField(max_length=255, null=True, blank=True)
    condition = models.CharField(max_length=255, null=True, blank=True)
    severity = models.CharField(max_length=255, null=True, blank=True)
    estimated_price = models.IntegerField(null=True, blank=True)
    effective_damage_rule = models.ForeignKey('DamageRule', null=True, blank=True)
    mannual = models.NullBooleanField(null=True, blank=True)


class Key(models.Model):
    car = models.ForeignKey('Car')
    name = models.CharField(max_length=255, null=True, blank=True)
    quantity = models.IntegerField(null=True, blank=True)


class Image(models.Model):
    car = models.ForeignKey('Car')
    link = models.URLField()
    show_to_customer = models.BooleanField(default=True)


class StockImageInfo(models.Model):
    stock_image = models.ForeignKey('StockImage')
    model = models.ForeignKey('CarModel')
    trim = models.ForeignKey('CarTrim', null=True, blank=True)
    year = models.IntegerField()


class StockImage(models.Model):
    VIEW_CHOICES = (
        ('F', 'FRONT'),
        ('B', 'BACK'),
        ('S', 'SIDE'),
    )

    VIEW_CHOICES = (
        ('F', 'FRONT'),
        ('B', 'BACK'),
        ('S', 'SIDE'),
    )

    image = models.ImageField(upload_to='stock_images/')
    view_type = models.CharField(max_length=7, choices=VIEW_CHOICES)
    colors = models.ManyToManyField('Color')


class Color(models.Model):
    name = models.CharField(max_length=127)

    def __unicode__(self):
        return self.name

    class Meta:
        ordering = ['name']


class Contact(models.Model):
    car = models.ForeignKey('Car')
    first_name = models.CharField(max_length=255, null=True, blank=True)
    last_name = models.CharField(max_length=255, null=True, blank=True)
    phone_number = models.CharField(max_length=255, null=True, blank=True)
    email = models.CharField(max_length=255, null=True, blank=True)
    comment = models.TextField(null=True, blank=True)
    is_read = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)

    def __unicode__(self):
        return self.first_name + ' ' + self.last_name + ' ' + str(self.created_at)


class DamageRule(models.Model):
    part = models.CharField(max_length=2000, default='.*')
    condition = models.CharField(max_length=2000, default='.*')
    severity = models.CharField(max_length=2000, default='.*')
    car_model = models.CharField(max_length=2000, default='.*')
    price = models.IntegerField()
    mannual = models.BooleanField(default=False)

    def __unicode__(self):
        return self.part + ' ' + self.condition + ' ' + self.severity + ' ' + self.car_model + ' ' + str(self.price)


class Carfax(models.Model):
    car = models.OneToOneField('Car', null=True, blank=True)
    ownership_text = models.CharField(max_length=255, null=True, blank=True)

administrator/templates/administrator/actions.html
{% extends 'administrator/layout/layout.html' %}
{% block 'title' %}Actions{% endblock %}
{% block 'main' %}
    <div class="container">
        <div>
            <form action="#" method="post" style="display: inline-block;">
                {% csrf_token %}
                <input type="hidden" name="action" value="calculate_mo_prices" />
                <button class="btn btn-danger">
                    Calculate mo prices
                </button>
            </form>
            <form action="#" method="post" style="display: inline-block;">
                {% csrf_token %}
                <input type="hidden" name="action" value="calculate_bg_prices" />
                <button class="btn btn-danger">
                    Calculate bg prices
                </button>
            </form>
            <form action="#" method="post" style="display: inline-block;">
                {% csrf_token %}
                <input type="hidden" name="action" value="calculate_ove_prices" />
                <button class="btn btn-danger">
                    Calculate ove prices
                </button>
            </form>
            <form action="#" method="post" style="display: inline-block;">
                {% csrf_token %}
                <input type="hidden" name="action" value="calculate_ade_prices" />
                <button class="btn btn-danger">
                    Calculate ade prices
                </button>
            </form>
        </div>
        <hr/>
        <div>
            <form action="#" method="post" style="display: inline-block;">
                {% csrf_token %}
                <input type="hidden" name="action" value="mo_all" />
                <button class="btn btn-danger">
                    mo All
                </button>
            </form>
            <form action="#" method="post" style="display: inline-block;">
                {% csrf_token %}
                <input type="hidden" name="action" value="bg_all" />
                <button class="btn btn-danger">
                    bg All
                </button>
            </form>
            <form action="#" method="post" style="display: inline-block;">
                {% csrf_token %}
                <input type="hidden" name="action" value="ove_all" />
                <button class="btn btn-danger">
                    ove All
                </button>
            </form>
            <form action="#" method="post" style="display: inline-block;">
                {% csrf_token %}
                <input type="hidden" name="action" value="ade_all" />
                <button class="btn btn-danger">
                    ade All
                </button>
            </form>
        </div>
    </div>
{% endblock %}

administrator/templates/administrator/car_list.html
{% extends 'administrator/layout/layout.html' %}
{% load is_limited_employee %}
{% load scale %}

{% block 'title' %}{{ request.GET.site }} Car List{% endblock %}
{% block 'main' %}
    <div class="container">
        <table class="table">
            <thead>
            <tr>
                <th>#</th>
                <th>Car model</th>
                <th>VIN</th>
                <th>Grade</th>
                <th>Status</th>
                <th>Make</th>
                <th>Created At</th>
                <th>Updated At</th>
                <th>View</th>
            </tr>
            </thead>
            <tbody>
            {% for car in cars %}
                <tr>
                    <td>
                        {{ forloop.counter }}
                    </td>
                    <td>
                        {{ car.car_model }}
                    </td>
                    <td>
                        {{ car.vin }}
                    </td>
                    <td>
                        {% if not user|is_limited_employee %}
                        {{ car.grade }}
                        {% else %}
                        {{ car.grade|grade_scale }}
                        {% endif %}

                    </td>
                    <td>
                        {% if car.is_rejected and car.is_it_available %}
                            <span style="color: red;">Rejected
                        {% elif not car.eligible_to_display and car.is_it_available %}
                            <span style="color: burlywood;">Unresolved damages
                        {% elif car.is_it_available %}
                            <span style="color: green;">Available
                        {% else %}
                            <span style="color: darkred;"> ---
                        {% endif %}

                        {% if car.removed_permanently %}
                            <span style="color: red;">(REMOVED PERMANENTLY)</span>
                        {% endif %}

                        {% if car.remain_permatently %}
                            <span style="color: green;">(KEEP FOREVER)</span>
                        {% endif %}

                        {% if car.remain_until %}
                            <span style="color: green;">(Avail till {{ car.remain_until }})</span>
                        {% endif %}
                            </span>
                    </td>
                    <td>
                        {{ car.make }}
                    </td>
                    <td>
                        {{ car.created_at }}
                    </td>
                    <td>
                        {% if car.last_updated_time != None %}
                        {{ car.last_updated_time }}
                        {% else %}
                        ---
                        {% endif %}
                    </td>
                    <td>
                        <a href="{% url 'search_car' %}?id={{ car.id }}">View Car</a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

administrator/templates/administrator/contacts.html
{% extends 'administrator/layout/layout.html' %}
{% block 'title' %}Contacts / Requests{% endblock %}
{% block 'main' %}

    <table class="table table-bordered table-hover dataTable" role="grid">
        <thead>
        <tr role="row">
            <th class="sorting_asc" tabindex="0" rowspan="1" colspan="1" aria-sort="ascending">First Name</th>
            <th class="sorting" tabindex="0" rowspan="1" colspan="1">Last Name</th>
            <th class="sorting" tabindex="0" rowspan="1" colspan="1">Email</th>
            <th class="sorting" tabindex="0" rowspan="1" colspan="1">Phone</th>
            <th class="sorting" tabindex="0" rowspan="1" colspan="1">Comment</th>
            <th class="sorting" tabindex="0" rowspan="1" colspan="1">Time</th>
            <th class="sorting" tabindex="0" rowspan="1" colspan="1">Car</th>
        </tr>
        </thead>
        <tbody>
            {% for contact in contacts %}
            {% if forloop.counter|divisibleby:2 == 0 %}
            <tr role="row" class="even">
            {% else %}
            <tr role="row" class="odd">
            {% endif %}
                <td class="sorting_1">
                    {{ contact.first_name }}
                </td>
                <td>
                    {{ contact.last_name }}
                </td>
                <td>
                    {{ contact.email }}
                </td>
                <td>
                    {{ contact.phone_number }}
                </td>
                <td>
                    {{ contact.comment }}
                </td>
                <td style="font-size: 13px;">
                    {{ contact.created_at }}
                </td>
                <td>
                    <a href="{% url 'search_car' %}?stock_number={{ contact.car.stock_number }}">View</a>
                </td>
            </tr>
          {% endfor %}


        </tbody>
    </table>

{% endblock %}

administrator/templates/administrator/dashboard.html
{% extends 'administrator/layout/layout.html' %}
{% load is_limited_employee %}

{% block 'title' %}Dashboard{% endblock %}
{% block 'main' %}
    <!-- Small boxes (Stat box) -->
    <div class="row">
        <div class="col-lg-4 col-xs-6">
            <!-- small box -->
            <div class="small-box bg-aqua">
                <div class="inner">
                    <h3>{{ cars_count }}</h3>
                    <p>Total # of Cars on Website</p>
                </div>
                <div class="icon">
                    <i class="ion ion-model-s"></i>
                </div>
                <a href="#" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
            </div>
        </div>
        {% if not user|is_limited_employee %}
        <!-- ./col -->
        <div class="col-lg-4 col-xs-6">
            <!-- small box -->
            <div class="small-box bg-green">
                <div class="inner">
                    <h3>{{ damage_count }}</h3>

                    <p># of Damages</p>
                </div>
                <div class="icon">
                    <i class="ion ion-wrench"></i>
                </div>
                <a href="{% url 'fill_damages' %}" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
            </div>
        </div>
        {% endif %}
        <!-- ./col -->
        <div class="col-lg-4 col-xs-6">
            <!-- small box -->
            <div class="small-box bg-yellow">
                <div class="inner">
                    <h3>{{ contacts_count }}</h3>

                    <p>Total # of Contacts</p>
                </div>
                <div class="icon">
                    <i class="ion ion-chatbubbles"></i>
                </div>
                <a href="{% url 'contacts' %}" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
            </div>
        </div>
{#        <!-- ./col -->#}
{#        <div class="col-lg-4 col-xs-6">#}
{#            <!-- small box -->#}
{#            <div class="small-box bg-red">#}
{#                <div class="inner">#}
{#                    <h3>65</h3>#}
{##}
{#                    <p>Unique Visitors</p>#}
{#                </div>#}
{#                <div class="icon">#}
{#                    <i class="ion ion-pie-graph"></i>#}
{#                </div>#}
{#                <a href="#" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>#}
{#            </div>#}
{#        </div>#}
{#        <!-- ./col -->#}
    </div>
    
    {% if not user|is_limited_employee %}
    <!-- /.row -->
    <div class="row">
        <div class="col-lg-4 col-xs-4">
            <h4>
                Crawlers Status
            </h4>
            <ul class="list-group">
            {% for crawler in crawlers %}
                <li class="list-group-item">
                    <span>{{ crawler.name }}:</span>
                    {% if crawler.status == "RUNNING" %}
                    <span style="color: orangered">
                        {{ crawler.status }}
                    </span>
                    <span>
                        (Started at {{ crawler.last_run }})
                    </span>
                    {% else %}
                    <span>
                        {{ crawler.status }}
                    </span>
                    {% endif %}
                </li>
            {% endfor %}
            </ul>
        </div>
    </div>
    {% endif %}
{% endblock %}

administrator/templates/administrator/fill_damages.html
{% extends 'administrator/layout/layout.html' %}
{% block 'title' %}Damages ({{ damage_count }}){% endblock %}
{% block 'main' %}
    <div class="container">
        <table class="table">
            <thead>
            <tr>
                {#                <th>id</th>#}
                <th>Car model</th>
                <th>Damage</th>
                <th>Condition</th>
                <th>Severity</th>
                <th>Rule</th>
                <th>Car</th>
            </tr>
            </thead>
            <tbody>
            {% for car in cars %}
                {% for damage in car.damage_set.all %}
                    {% if damage.estimated_price == None %}
                        <tr>
                            {#                            <td>#}
                            {#                                {{ damage.id }}#}
                            {#                            </td>#}
                            <td class="car_model_col">
                                {{ car.car_model }}
                            </td>
                            <td class="part_col">
                                {{ damage.part }}
                            </td>
                            <td class="condition_col">
                                {{ damage.condition }}
                            </td>
                            <td class="severity_col">
                                {{ damage.severity }}
                            </td>
                            <td>
                                <button class="btn btn-success add_rule" data-car-id="{{ car.id }}">add rule</button>
                                {#                                <input type="number" value="{{ damage.estimated_price }}" name="{{ damage.id }}"/>#}
                                {#                                {{ damage.mannual }}#}
                            </td>
                            <td>
                                <a href="{% url 'search_car' %}?id={{ car.id }}">View Car</a>
                            </td>
                        </tr>
                    {% endif %}
                {% endfor %}
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

{% block 'js' %}
    <script>
        $('.add_rule').click(function (e) {
            var car_model = $(this).parent().parent().find('.car_model_col').html().replace(/\s+/g, ' ').trim();
            var part = $(this).parent().parent().find('.part_col').html().replace(/\s+/g, ' ').trim();
            var condition = $(this).parent().parent().find('.condition_col').html().replace(/\s+/g, ' ').trim();
            var severity = $(this).parent().parent().find('.severity_col').html().replace(/\s+/g, ' ').trim();

            var dialog = bootbox.dialog({
                message: "<h4>Add New Damage Rule</h4>\
                <table class='table'>\
                    <tr>\
                    <th>Car model</th><th>Damage</th><th>Condition</th><th>Severity</th>\
                    </tr>\
                    <tr>\
                    <td>"
                + car_model +
                "</td>\
                <td>"
                + part +
                "</td>\
                <td>"
                + condition +
                "</td>\
                <td>"
                + severity +
                "</td>\
                </tr>\
                </table>\
                <form action='#' method='post' class='add-damage-rule-forms'>\
                {% csrf_token %}\
                <input type='hidden' name='car_id' value='" + $(this).attr('data-car-id') + "' />\
            </div>\
        <table>\
        <hr>\
            <div class='form-group'>\
                <div>\
                    <label>Damage</label> <input type='radio' checked=checked name='consider_damage' value='1' />\
                    ---- OR ----    all damages <input type='radio' name='consider_damage' value='0' />\
                </div>\
                <input type='text' name='part' value='" + part + "'/>\
            </div>\
            <hr>\
            <div class='form-group'>\
                <div>\
                    <label>Condition</label> <input type='radio' checked=checked name='consider_condition' value='1' />\
                    ---- OR ----    all conditions <input type='radio' name='consider_condition' value='0' />\
                </div>\
                <input type='text' name='condition' value='" + condition + "'/>\
            </div>\
            <hr>\
            <div class='form-group'>\
                <div>\
                <label>Severity</label> <input type='radio' checked=checked name='consider_severity' value='1' />\
                    ---- OR ----    all severities <input type='radio' name='consider_severity' value='0' />\
                </div>\
                <div>\
                    <input type='radio' name='severity_type' value='text' checked=checked />\
                    <input type='text' name='severity' value='" + severity + "'/> (Text)\
                </div>\
                <div>\
                    <input type='radio' name='severity_type' value='number' />\
                    <select name='number_operation'>\
                        <option value='G'>Greater than</option>\
                        <option value='GE'>Greater than or equal</option>\
                        <option value='L'>Less than</option>\
                        <option value='LE'>Less than equal</option>\
                    </select>\
                    <input type='number' step='0.001' name='severity_number' value='number'/> (Number)\
                </div>\
                <div>\
                    <input type='radio' name='severity_type' value='inch' />\
                    <select name='inch_operation'>\
                        <option value='G'>Greater than</option>\
                        <option value='GE'>Greater than or equal</option>\
                        <option value='L'>Less than</option>\
                        <option value='LE'>Less than equal</option>\
                    </select>\
                    <input type='number' step='0.001' name='severity_inch' value='inch'/>\
                    (Inch)\
                </div>\
            </div>\
            <div class='form-group'>\
                <label>PRICE</label>\
                <input class='form-control' type='number' required=required name='price'/>\
            </div>\
            <button type='submit' class='btn btn-success btn-submit-request'>\
                Submit Rule\
            </button>\
        </table>\
        \
    </form>",
            });
        });
    </script>

    <script>
        $(document).on('submit', '.add-damage-rule-forms', function (e) {
            var btn = $(this).find('button[type=submit]')
            btn.attr('disabled', 'disabled');
            btn.text('Please Wait...');
        });
    </script>

{% endblock %}