main/urls.py
from django.conf.urls import url, include
from main import views
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    url(r'^$', views.home_page, name='home_page'),
    url(r'^browse$', views.car_browse, name='car_browse'),
    url(r'^buying_process', views.buying_process, name='buying_process'),
    url(r'^finance', views.finance, name='finance'),
    # url(r'^about_us', views.about_us, name='about_us'),
    url(r'^faq', views.faq, name='faq'),
    url(r'^car/(?P<car_id>[0-9]+)$', views.car_profile, name='car_profile'),
    url(r'^car/customer/(?P<unique_customer_link>[a-zA-Z0-9]+)$', views.customer_car_view, name='customer_car_view'),
    url(r'^ajax_load_cars$', views.ajax_load_cars, name='ajax_load_cars'),
    url(r'^ajax_load_models$', views.ajax_load_models, name='ajax_load_models'),
    url(r'^showroom/(?P<car_id>[0-9]+)$', views.showroom, name='showroom'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^login/$', views.selfLogin, name='login'),
    url(r'^logout/$', views.selfLogout, name='logout'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

crawler/models.py
from __future__ import unicode_literals

from django.db import models
from django.db.models import Q
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.contrib.staticfiles.templatetags.staticfiles import static
from django.utils import timezone

import managers
import random


class Car(models.Model):
    mo_car_id = models.IntegerField(null=True, blank=True)
    ove_car_id = models.IntegerField(null=True, blank=True)
    ade_car_id = models.IntegerField(null=True, blank=True)
    bg_car_id = models.IntegerField(null=True, blank=True)
    vin = models.CharField(max_length=31)
    stock_number = models.CharField(max_length=31, null=True, blank=True)
    make = models.ForeignKey('Make', null=True, blank=True)
    model = models.ForeignKey('CarModel', null=True, blank=True)
    trim = models.ForeignKey('CarTrim', null=True, blank=True)
    car_model = models.CharField(max_length=255)
    original_price = models.IntegerField(null=True, blank=True)
    final_price = models.IntegerField(null=True, blank=True)
    year = models.SmallIntegerField(null=True, blank=True)
    location = models.ForeignKey('Location', null=True, blank=True)
    grade = models.FloatField(null=True, blank=True)
    last_checking = models.DateTimeField()
    is_it_available = models.BooleanField(default=True)
    available_on_mo = models.BooleanField(default=False)
    available_on_bg = models.BooleanField(default=False)
    available_on_ove = models.BooleanField(default=False)
    available_on_ade = models.BooleanField(default=False)
    mo_removed_at = models.DateTimeField(null=True, blank=True)
    bg_removed_at = models.DateTimeField(null=True, blank=True)
    ove_removed_at = models.DateTimeField(null=True, blank=True)
    ade_removed_at = models.DateTimeField(null=True, blank=True)
    last_updated_time = models.DateTimeField(null=True, blank=True)
    is_rejected = models.BooleanField(default=False)
    rejection_reason = models.CharField(max_length=1023, null=True, blank=True)
    eligible_to_display = models.BooleanField(default=False)
    removed_permanently = models.BooleanField(default=False)
    remain_permatently = models.BooleanField(default=False)
    remain_until = models.DateTimeField(null=True, blank=True)
    unique_customer_link = models.CharField(max_length=255, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    objects = managers.CarManager()
    
    def __unicode__(self):
        return str(self.id)

    def save(self, *args, **kwargs):
        if self.stock_number == None:
            self.stock_number = self.generate_stock_number()
        super(Car, self).save(*args, **kwargs)

    def is_available_eligible(self):
        return (self.is_it_available == True\
                or (self.remain_until != None and self.remain_until > timezone.now())\
                or self.remain_permatently == True)\
               and self.is_rejected == False and self.eligible_to_display == True and self.make.is_visible == True\
               and self.removed_permanently == False

    def generate_stock_number(self):
        return chr(65 + int(random.random() * 26)) + chr(65 + int(random.random() * 26)) + str(
            int(random.random() * 10)) + str(int(random.random() * 10)) + str(int(random.random() * 10)) + str(
            int(random.random() * 10))

    def generate_unique_cutomer_link(self):
        string = []
        id_str = str(self.id)
        chars_count = 12
        mod = chars_count / len(id_str)
        for i in xrange(12):
            string.append(chr(97 + int(random.random() * 26)))

        return ''.join(string[:8]) + id_str + ''.join(string[8:])

    def stock_image(self):
        year = self.year
        car_model = self.model
        car_trim = self.trim

        stock_image_infos = StockImageInfo.objects.filter(
            Q(model=car_model) & (Q(trim=None) | Q(trim=car_trim)) & Q(year=year) & Q(stock_image__view_type='F') & Q(
                stock_image__colors__name__iexact=self.cardetail.exterior))

        if len(stock_image_infos) > 0:
            for stock_image_info in stock_image_infos:
                if stock_image_info.trim != None:
                    return stock_image_info.stock_image.image.url

            return stock_image_infos.first().stock_image.image.url

        return static('img/no_image.png')


class CarDetail(models.Model):
    car = models.OneToOneField('Car')
    detail_html = models.FilePathField()
    vehicle_options = models.TextField(null=True, blank=True)
    miles = models.IntegerField(null=True, blank=True)
    exterior = models.CharField(max_length=255, null=True, blank=True)
    interior = models.CharField(max_length=255, null=True, blank=True)
    engine = models.CharField(max_length=255, null=True, blank=True)
    odor = models.CharField(max_length=255, null=True, blank=True)
    msrp = models.IntegerField(null=True, blank=True)
    announcements = models.CharField(max_length=1000, null=True, blank=True)
    value_added_options = models.CharField(max_length=1000, null=True, blank=True)
    warranty_date = models.DateField(null=True, blank=True)
    drive = models.CharField(max_length=255, null=True, blank=True)
    keys = models.CharField(max_length=255, null=True, blank=True)


class Location(models.Model):
    name = models.CharField(max_length=255)
    shipping_cost = models.IntegerField(default=0)

    def __unicode__(self):
        return self.name


class Make(models.Model):
    name = models.CharField(max_length=255)
    fuel_name = models.CharField(max_length=255)
    is_visible = models.BooleanField(default=True)

    def __unicode__(self):
        return self.name


class CarModel(models.Model):
    name = models.CharField(max_length=255)
    fuel_name = models.CharField(max_length=255)
    make = models.ForeignKey('Make')

    def __unicode__(self):
        return self.name + ', ' + self.make.name


class CarTrim(models.Model):
    name = models.CharField(max_length=255)
    model = models.ForeignKey('CarModel')

    def __unicode__(self):
        return self.name + ', ' + self.model.name + ', ' + self.model.make.name


class Tire(models.Model):
    TIRE_CHOICES = (
        ('LFRNT', 'LFRNT'),
        ('LREAR', 'LREAR'),
        ('RFRNT', 'RFRNT'),
        ('RREAR', 'RREAR'),
        ('SPARE', 'SPARE'),
    )

    car = models.ForeignKey('Car')
    type = models.CharField(max_length=31, choices=TIRE_CHOICES)
    tread = models.CharField(max_length=31, null=True, blank=True)
    brand = models.CharField(max_length=31, null=True, blank=True)
    size = models.CharField(max_length=31, null=True, blank=True)


class Repair(models.Model):
    car = models.ForeignKey('Car')
    repaired = models.CharField(max_length=255)
    condition = models.CharField(max_length=255, null=True, blank=True)
    severity = models.CharField(max_length=255, null=True, blank=True)
    repair_type = models.CharField(max_length=255, null=True, blank=True)


class Damage(models.Model):
    car = models.ForeignKey('Car')
    part = models.CharField(max_length=255, null=True, blank=True)
    condition = models.CharField(max_length=255, null=True, blank=True)
    severity = models.CharField(max_length=255, null=True, blank=True)
    estimated_price = models.IntegerField(null=True, blank=True)
    effective_damage_rule = models.ForeignKey('DamageRule', null=True, blank=True)
    mannual = models.NullBooleanField(null=True, blank=True)


class Key(models.Model):
    car = models.ForeignKey('Car')
    name = models.CharField(max_length=255, null=True, blank=True)
    quantity = models.IntegerField(null=True, blank=True)


class Image(models.Model):
    car = models.ForeignKey('Car')
    link = models.URLField()
    show_to_customer = models.BooleanField(default=True)


class StockImageInfo(models.Model):
    stock_image = models.ForeignKey('StockImage')
    model = models.ForeignKey('CarModel')
    trim = models.ForeignKey('CarTrim', null=True, blank=True)
    year = models.IntegerField()


class StockImage(models.Model):
    VIEW_CHOICES = (
        ('F', 'FRONT'),
        ('B', 'BACK'),
        ('S', 'SIDE'),
    )

    VIEW_CHOICES = (
        ('F', 'FRONT'),
        ('B', 'BACK'),
        ('S', 'SIDE'),
    )

    image = models.ImageField(upload_to='stock_images/')
    view_type = models.CharField(max_length=7, choices=VIEW_CHOICES)
    colors = models.ManyToManyField('Color')


class Color(models.Model):
    name = models.CharField(max_length=127)

    def __unicode__(self):
        return self.name

    class Meta:
        ordering = ['name']


class Contact(models.Model):
    car = models.ForeignKey('Car')
    first_name = models.CharField(max_length=255, null=True, blank=True)
    last_name = models.CharField(max_length=255, null=True, blank=True)
    phone_number = models.CharField(max_length=255, null=True, blank=True)
    email = models.CharField(max_length=255, null=True, blank=True)
    comment = models.TextField(null=True, blank=True)
    is_read = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)

    def __unicode__(self):
        return self.first_name + ' ' + self.last_name + ' ' + str(self.created_at)


class DamageRule(models.Model):
    part = models.CharField(max_length=2000, default='.*')
    condition = models.CharField(max_length=2000, default='.*')
    severity = models.CharField(max_length=2000, default='.*')
    car_model = models.CharField(max_length=2000, default='.*')
    price = models.IntegerField()
    mannual = models.BooleanField(default=False)

    def __unicode__(self):
        return self.part + ' ' + self.condition + ' ' + self.severity + ' ' + self.car_model + ' ' + str(self.price)


class Carfax(models.Model):
    car = models.OneToOneField('Car', null=True, blank=True)
    ownership_text = models.CharField(max_length=255, null=True, blank=True)

main/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.core.exceptions import ObjectDoesNotExist
import crawler

class FAQCategory(models.Model):
    name = models.CharField(max_length=255)
    fa_icon = models.CharField(max_length=63)
    order = models.IntegerField(default=0)

    class Meta:
        ordering = ('order', 'id', )

    def __unicode__(self):
        return self.name

class FAQ(models.Model):
    faq_category = models.ForeignKey('FAQCategory')
    question = models.CharField(max_length=1023)
    answer = models.TextField()
    order = models.IntegerField(default=0)

    class Meta:
        ordering = ('order', 'id', )

    def __unicode__(self):
        return self.question

class Account(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, blank=True, null=True)
    car = models.ManyToManyField('crawler.Car', through='UserCarRecommendation', blank=True)
    phone = models.CharField(max_length=20, blank=True, null=True)
    '''todo: change phone field type to something smarter, 
       maybe charfield with regex or regexfield'''

    def __unicode__(self):
        return self.user.username

'''Hookup create and save to our account model'''
@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Account.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    try:
        instance.account.save()
    except ObjectDoesNotExist:
        pass

'''Create model to govern manytomany relationship'''
class UserCarRecommendation(models.Model):
    car = models.ForeignKey('crawler.Car',blank=True,null=True)
    account = models.ForeignKey(Account,blank=True,null=True)
    #additional fields will be added later

    def __unicode__(self):
        return str(self.account) + ": " + str(self.car.id)

main/forms.py
from django import forms
from django.contrib.auth.models import User
from models import Account

class UserCreationFormWithEmail(forms.ModelForm):
	'''UserCreationForm with email as username rather than a seperate username'''
	"""
    A form that creates a user, with no privileges, from the given email and
    password.
    """
	error_messages = {
		'password_mismatch': ("The two password fields didn't match."),
	}
	first_name = forms.CharField(label='First Name', max_length=30)
	last_name = forms.CharField(label='Last Name', max_length=30)
	username = forms.EmailField(label=('Email'), max_length=64, help_text='Input email here')
	password1 = forms.CharField(label= ('Password'),
		widget=forms.PasswordInput)
	password2 = forms.CharField(label= ('Retype Password'),
		widget=forms.PasswordInput,
		help_text= ('Enter the same password as above, for verification.'))
	car_id = forms.CharField(label= ('car_id_test'), help_text= ('This should not be in production build'))
	phone = forms.CharField(label=('Phone Number'), max_length=20, required=False,help_text='Optional')

	class Meta:
		model = User
		fields = ('first_name','last_name','username', 'password1', 'password2','car_id','phone')

	def clean_email(self):
		email = self.cleaned_data['username']
		return email

	def clean_password2(self):
		password1 = self.cleaned_data.get('password1')
		password2 = self.cleaned_data.get('password2')
		if password1 and password2 and password1 != password2:
			raise forms.ValidationError(
				self.error_messages['password_mismatch'],
				code='password_mismatch',
			)
		return password2

	def save(self, commit=True):
		user = super(UserCreationFormWithEmail, self).save(commit=False)
		user.set_password(self.cleaned_data['password1'])
		if commit:
			user.save()
		return user

class SimpleUserCreationFormWithEmail(forms.ModelForm):
	'''UserCreationForm with email as username rather than a seperate username'''
	"""
    A form that creates a user, with no privileges, from the given email and
    password.
    """
	error_messages = {
		'password_mismatch': ("The two password fields didn't match."),
	}
	first_name = forms.CharField(label='First Name', max_length=30,widget=forms.TextInput(attrs={'class':'form-control'}))
	last_name = forms.CharField(label='Last Name', max_length=30,widget=forms.TextInput(attrs={'class':'form-control'}))
	username = forms.EmailField(label=('Email'), max_length=64, widget=forms.TextInput(attrs={'class':'form-control'}))
	password1 = forms.CharField(label= ('Password'),		widget=forms.PasswordInput(attrs={'class':'form-control'}))
	password2 = forms.CharField(label= ('Retype Password'),		widget=forms.PasswordInput(attrs={'class':'form-control'}),
		help_text= ('Enter the same password as above, for verification.'))


	class Meta:
		model = User
		fields = ('first_name','last_name','username', 'password1', 'password2')

	def clean_email(self):
		email = self.cleaned_data['username']
		return email

	def clean_password2(self):
		password1 = self.cleaned_data.get('password1')
		password2 = self.cleaned_data.get('password2')
		if password1 and password2 and password1 != password2:
			raise forms.ValidationError(
				self.error_messages['password_mismatch'],
				code='password_mismatch',
			)
		return password2

	def save(self, commit=True):
		user = super(SimpleUserCreationFormWithEmail, self).save(commit=False)
		user.set_password(self.cleaned_data['password1'])
		if commit:
			user.save()
		return user

class SimpleUserLoginFormWithEmail(forms.ModelForm):
	'''UserCreationForm with email as username rather than a seperate username'''
	"""
    A form that creates a user, with no privileges, from the given email and
    password.
    """
	error_messages = {
		'password_mismatch': ("The two password fields didn't match."),
	}
	username = forms.EmailField(label=('Email'), max_length=64, widget=forms.TextInput(attrs={'class':'form-control'}))
	password1 = forms.CharField(label= ('Password'),widget=forms.PasswordInput(attrs={'class':'form-control'}))

	class Meta:
		model = User
		fields = ('username', 'password1')

	def clean_email(self):
		email = self.cleaned_data['username']
		return email

	def save(self, commit=True):
		user = super(SimpleUserLoginFormWithEmail, self).save(commit=False)
		user.set_password(self.cleaned_data['password1'])
		if commit:
			user.save()
		return user

main/templates/main/customer_car_view.html
{% extends 'main/layout/layout.html' %}
{% load staticfiles %}
{% load normalize_price %}
{% load int_tags %}
{% load scale %}
{% load is_superuser %}

{% block 'title' %}Customer Link | {{ car.car_model }} {{ block.super }}{% endblock %}

{% block 'main' %}
    <div class="container" style="border: 1px solid #ccc; border-radius: 10px; padding: 0px 25px 0px 25px;">
        {% if car.is_available_eligible %}
            <header style="margin-top: 50px;">
                <img src="{% static 'img/carboi_logo.png' %}" height="50px"/>
            </header>

            <br><br>

            <h6 style="color: white; background-color: #0391FD; border: 1px solid #eee; padding: 10px 10px;">Vehicle
                Details</h6>
            <br>

            <div class="row">
                <div class="col-md-4">
                    <ul class="list-group">
                        <li class="list-group-item">Make: {{ car.make }}</li>
                        <li class="list-group-item">Model: {{ car.car_model }}</li>
                        <li class="list-group-item">Year: {{ car.year }}</li>
                        <li class="list-group-item">Price:
                            ${{ car.final_price|normalize_price|thousands_separator }}</li>
                    </ul>
                </div>
                <div class="col-md-4" style="text-align: center;">
                    <div>
                        Auto Grade
                    </div>
                    <div style="position: relative; display: inline-block;">
                        <img src="{% static 'img/grade.png' %}" height="200px;"/>
                        <span style="font-size: 27px; font-weight: bold; color: #35B729; position: absolute; top: 56px; left:79px;">{{ car.grade|grade_scale }}</span>
                    </div>
                </div>
                <div class="col-md-4">
                    <ul class="list-group">
                        <li class="list-group-item">VIN : {{ car.vin }}</li>
                        <li class="list-group-item">Mileage: {{ car.cardetail.miles|human_format }}</li>
                        <li class="list-group-item">Warranty: Yes</li>
                        <li class="list-group-item">Stock Number: {{ car.stock_number }}</li>
                    </ul>
                </div>
            </div>
            <br>

            {#            <h3 style="margin-top:50px; margin-bottom:25px;">#}
            {#                {{ car.car_model }}#}
            {#            </h3>#}

            <br><br>

            {% if car.image_set.all|length > 0 %}
                <h6 style="color: white; background-color: #0391FD; border: 1px solid #eee; padding: 10px 10px">
                    Vehicle Images
                </h6>
                <br>

                {% for img in car.image_set.all %}
                    {% if not user|is_superuser and img.show_to_customer %}
                        <a href="{{ img.link }}" target="_blank">
                            <img src="{{ img.link }}" width="150px"/>
                        </a>
                    {% elif user|is_superuser %}
                        <div style="display: inline-block;">
                            <div style="text-align: center; margin-bottom: 15px;">
                                <a href="{{ img.link }}" target="_blank">
                                    <img src="{{ img.link }}" width="150px"
                                         style="display: block; margin-bottom: 10px;"/>
                                </a>
                                <form action="#" method="post">
                                    {% csrf_token %}
                                    <input type="hidden" name="img_id" value="{{ img.id }}"/>
                                    {% if img.show_to_customer %}
                                        <input type="hidden" name="action" value="remove"/>
                                        <button type="submit" class="btn btn-danger"
                                                style="display: block; width: 100%; cursor: pointer;">Remove
                                        </button>
                                    {% else %}
                                        <input type="hidden" name="action" value="add"/>
                                        <button type="submit" class="btn btn-success"
                                                style="display: block; width: 100%; cursor: pointer;">Add
                                        </button>
                                    {% endif %}
                                </form>
                            </div>
                        </div>
                        {#                        <a href="{{ img.link }}" target="_blank">#}
                        {#                            #}
                        {#                        </a>#}
                        {#                        <button>Remove This</button>#}
                    {% endif %}
                {% endfor %}
            {% endif %}

            {% if vehicle_options|length > 0 %}
                <br><br><br>
                <div>
                    <h6 style="color: white; background-color: #0391FD; border: 1px solid #eee; padding: 10px 10px">
                        Vehicle Options
                    </h6>
                    <table class="table table-bordered">
                        {% for vehicle_option in vehicle_options %}
                            {% if forloop.counter0|divisibleby:3 %}
                                <tr>
                            {% endif %}
                        <td>
                    <span style="font-size: 14px;">
                        {{ vehicle_option }}
                    </span>
                        </td>
                        {% if forloop.counter0|add:1|divisibleby:3 %}
                            </tr>
                        {% endif %}
                        {% endfor %}
                    </table>
                    <br>
                </div>
            {% endif %}

            {% if car.cardetail.value_added_options %}
                <span style="font-weight: bold;">Value Added Options:</span> {{ car.cardetail.value_added_options }}
                <br>
            {% endif %}

            {% if car.carfax %}
                <br>
                <br>
                <h6 style="color: white; background-color: #0391FD; border: 1px solid #eee; padding: 10px 10px;">
                    Carfax
                </h6>
                <div style="font-size: 13px; margin-left: 6px;">
                    <i class="fa fa-dot-circle-o"></i> Please ask your Account Manager for a complete copy of the report
                </div>
                <br>
                <table class="table">
                    <tbody>
                    {% if car.carfax.ownership_text %}
                        <tr>
                            <td>{{ car.carfax.ownership_number }}</td>
                            <td>{{ car.carfax.ownership_text }}</td>
                        </tr>
                    {% endif %}
                    {% if car.carfax.title_brand_text %}
                        <tr>
                            <td>
                                {% if car.carfax.title_brand_status == 'Green Check Mark' %}
                                    <img src="http://media.carfax.com/img/auction/blt_check.gif"/>
                                {% elif car.carfax.title_brand_status == 'Yellow Warning' %}
                                    <img src="http://media.carfax.com/img/auction/blt_ind.gif"/>
                                {% endif %}
                            </td>
                            <td>{{ car.carfax.title_brand_text }}</td>
                        </tr>
                    {% endif %}
                    {% if car.carfax.damage_text %}
                        <tr>
                            <td>
                                {% if car.carfax.damage_status == 'Green Check Mark' %}
                                    <img src="http://media.carfax.com/img/auction/blt_check.gif"/>
                                {% elif car.carfax.damage_status == 'Yellow Warning' %}
                                    <img src="http://media.carfax.com/img/auction/blt_ind.gif"/>
                                {% endif %}
                            </td>
                            <td>{{ car.carfax.damage_text }}</td>
                        </tr>
                    {% endif %}
                    {% if car.carfax.odometer_text %}
                        <tr>
                            <td>
                                {% if car.carfax.odometer_status == 'Green Check Mark' %}
                                    <img src="http://media.carfax.com/img/auction/blt_check.gif"/>
                                {% elif car.carfax.odometer_status == 'Yellow Warning' %}
                                    <img src="http://media.carfax.com/img/auction/blt_ind.gif"/>
                                {% endif %}
                            </td>
                            <td>{{ car.carfax.odometer_text }}</td>
                        </tr>
                    {% endif %}
                    {% if car.carfax.serviceRecords_text %}
                        <tr>
                            <td>
                                {% if car.carfax.serviceRecords_status == 'Green Check Mark' %}
                                    <img src="http://media.carfax.com/img/auction/blt_check.gif"/>
                                {% elif car.carfax.serviceRecords_status == 'Yellow Warning' %}
                                    <img src="http://media.carfax.com/img/auction/blt_ind.gif"/>
                                {% endif %}
                            </td>
                            <td>{{ car.carfax.serviceRecords_text }}</td>
                        </tr>
                    {% endif %}
                    {% if car.carfax.historyRecords_text %}
                        <tr>
                            <td>{{ car.carfax.historyRecords_number }}</td>
                            <td>{{ car.carfax.historyRecords_text }}</td>
                        </tr>
                    {% endif %}

                    </tbody>
                </table>
                <br><br>
            {% endif %}

            <br><br>
            </div>
        {% else %}
            SOLD

            {% if user|is_superuser %}
                <div>VIN: {{ car.vin }}</div>
                <div>link in administrator: <a href="http://carboi.com{% url 'search_car' %}?vin={{ car.vin }}">http://carboi.com{% url 'search_car' %}?vin={{ car.vin }}</a></div>
            {% endif %}
        {% endif %}
{% endblock %}

main/templates/main/faq.html
{% extends 'main/layout/layout.html' %}
{% load staticfiles %}

{% block 'title' %}FAQ {{ block.super }}{% endblock %}

{% block 'main' %}

<div class="wide-title faq-wide-title">
    <div class="wide-transparent-layer"></div>
    <h1>Frequently Asked Questions</h1>
</div>
<div class="container">
    <div class="row">
        <div class="col-3">
            <ul class="faq-category">
                {% for faq_category, faqs in faqs_list %}
                <li>
                    <a href="#FaqCategory{{ faq_category.id }}">{{ faq_category.name }}</a>
                </li>
                {% endfor %}
            </ul>
        </div>
        <div class="col-9">
            {% for faq_category, faqs in faqs_list %}
            <div class="faq-wrapper">
                <h4 class="faq-header" id="Home_Carboi_Works">
                    {{ faq_category.name }}
                </h4>

                {% for faq in faqs %}
                <div class="faq">
                    <div id="accordion" role="tablist" aria-multiselectable="true">
                      <div>
                        <div role="tab">
                          <h5 class="mb-0">
                            <a class="faq-question" data-toggle="collapse" data-parent="#accordion" href="#collapse{{ faq.id }}" aria-expanded="true" aria-controls="collapseOne">
                                <i class="fa fa-angle-down"></i> {{ faq.question }}
                            </a>
                          </h5>
                        </div>

                        <div id="collapse{{ faq.id }}" class="collapse" role="tabpanel" aria-labelledby="headingOne">
                          <div class="faq-ans-block">
                            {{ faq.answer|safe }}
                          </div>
                        </div>
                      </div>
                    </div>
                </div>
                {% endfor %}
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{{ block.super }}
{% endblock %}

main/templates/main/login.html
{% extends 'main/layout/layout.html' %}
{% load staticfiles %}
{% block 'title' %}Log In{% endblock %}

{% block 'main' %}
<div style="max-width: 600px; margin: 100px auto; 0 auto; padding:50px; background-color: #5ba1e6;">
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="btn btn-success form-control" type="submit" style="color: white;">Log In</button>
    <a style="color: white;" href="{% url 'signup' %}">Sign Up</a>
  </form>
</div>
{% endblock %}

main/templates/main/signup.html
{% extends 'main/layout/layout.html' %}
{% load staticfiles %}
{% block 'title' %}Sign Up{% endblock %}

{% block 'main' %}
<div style="max-width: 600px; margin: 100px auto; 0 auto; padding:50px; background-color: #5ba1e6;">
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="btn btn-success form-control" type="submit">Sign up</button>
  </form>
  </div>
{% endblock %}